<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
<script>
  new Promise((resolve, reject) => {
    // 执行异步操作代码, 如果成功了, 调用resolve(value)
    /*setTimeout(() => {
      resolve('成功的value')
    }, 1000)*/
    // 执行异步操作代码, 如果失败了, 调用reject(reason)
    setTimeout(() => {
      reject('失败的reason')
    }, 2000)
  }).then(
    value => {
      console.log('onResolved()1', value)
    }, // 成功的回调
    reason => {
      console.log('onRejected()1', reason)
      //      1). 函数执行抛出了异常  ==> 失败, reason就是抛出的异常
      // throw 1
      //      2). 函数执行返回一个失败的promise ==> 失败, reason就是返回的promise的reason
      // return Promise.reject(2)
      //      3). 函数执行返回一个成功的promise ==> 成功, value就是返回的promise的value
      //      return Promise.resolve(3)
      //      4). 函数执行返回其它任意值 ==> 成功, value就是返回的值
      //      return 4
    } // 失败的回调
  ).then(
    value => {
      console.log('onResolved()2', value)
    },
    reason => {
      console.log('onRejected()2', reason)
    }
  )


  /* 
  常用语法: Promise.all(promises)
    接收包含N个promise的数组, 返回一个新的promise
    只有当数组中所有promise成功了, 返回的promise才成功, value是所有成功promise的value的数组
    只要有一个promise失败了, 返回的promise就失败了, reason是失败的promise的reason
  */
  const p1 = Promise.resolve(1)
  const p2 = Promise.resolve(2)
  const p3 = Promise.reject(3)

  const p4 = Promise.all([p1, p2]) // p4成功了, value是[1,2]   为什么?
  const p5 = Promise.all([p1, p2, p3]) // p5失败了, reason是3  为什么?
</script>
</body>
</html>